on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy Files
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Deploy to Server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: 'f1176550'
          server: ${{ secrets.SERVER_IP }}
          remote_path: '/home/f1176550/domains/net-gazetteer.ru/public_html/'
          sftpArgs: '-o ConnectTimeout=5'
          password: ${{ secrets.FTP_PASSWORD }}
